; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .
default_envs = cardputer

[env:cardputer]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_src_filter = 
  +<platform/m5/src/*.cpp>
  +<core/src/*.cpp>

build_unflags = -std=gnu++11
build_flags =
  -I core/include
  -I core/src
  -I platform/m5/src
  -std=gnu++17

lib_deps =
  m5stack/M5Unified
  m5stack/M5Cardputer
